export const FILTER_VALUE_MAP = {
  accommodationType: {
    '호텔/리조트': 'HOTEL_RESORT',
    독채: 'DETACHED_HOUSE',
    풀빌라: 'FULL_VILLA',
    펜션: 'PENSION',
  },
  accommodationFacilities: {
    편의점: 'CONVENIENCE_STORE',
    '공용 수영장': 'PUBLIC_SWIMMING_POOL',
    바베큐: 'BARBECUE',
    피트니스: 'FITNESS',
    노래방: 'KARAOKE_ROOM',
    와이파이: 'WIFI',
    주차장: 'PARKING_LOT',
    무료주차: 'FREE_PARKING',
    유료주차: 'PAID_PARKING',
    조식: 'BREAKFAST',
    '픽업 서비스': 'PICKUP',
    족구장: 'FOOT_VOLLEYBALL_COURT',
  },
  accommodationPetFacilities: {
    '대형 운동장': 'EXERCISE_AREA',
    '전용 마당': 'EXCLUSIVE_YARD',
    놀이터: 'PLAYGROUND',
    샤워장: 'SHOWER_ROOM',
    수영장: 'SWIMMING_POOL',
    '미끄럼 방지 바닥': 'ANTI_SLIP_FLOOR',
    '펜스 설치 공간': 'FENCE_AREA',
    '돌봄 서비스': 'CARE_SERVICE',
    '펫 푸드 제공': 'PET_FOOD',
    '인근 동물병원': 'NEARBY_HOSPITAL',
  },
  roomFacilities: {
    스타일러: 'STYLER',
    냉장고: 'REFRIGERATOR',
    전기밥솥: 'RICE_COOKER',
    샤워실: 'SHOWER_ROOM',
    에어컨: 'AIR_CONDITIONER',
    TV: 'TV',
    와이파이: 'WIFI',
    욕실용품: 'BATHROOM_SUPPLIES',
    드라이기: 'DRYER',
    바베큐: 'BARBECUE',
    '객실 내 취사': 'POSSIBLE_COOK_IN_ROOM',
  },
  roomPetFacilities: {
    식기: 'FOOD_BOWL',
    배변용품: 'POTTY_SUPPLIES',
    장난감: 'TOY',
    침대: 'BED',
    드라이룸: 'DRY_ROOM',
    '미끄럼 방지 바닥': 'ANTI_SLIP_FLOOR',
    '펜스 설치 공간': 'FENCE_AREA',
    캣타워: 'CAT_TOWER',
    캣휠: 'CAT_WHEEL',
    빗: 'COMB',
    '강아지 계단': 'PET_STEPS',
  },
  hashtags: {
    가족여행: 'FAMILY_TRIP',
    스파: 'SPA',
    오션뷰: 'OCEAN_VIEW',
    파티룸: 'PARTY_ROOM',
    아늑한: 'COZY',
    모던한: 'MODERN',
    금연숙소: 'NO_SMOKING',
    포레스트뷰: 'FOREST_VIEW',
    감성숙소: 'EMOTIONAL',
  },
  allowPets: {
    대형견: 'LARGE_DOG',
    중형견: 'MEDIUM_DOG',
    소형견: 'SMALL_DOG',
    고양이: 'CAT',
  },
} as const;
